name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install
      - name: Build code
        run: |
          cd client
          npm run build
          cd ../server
          npm run build
